# Generated by Django 5.2.4 on 2025-08-07 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='Tugash vaqti')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Tasdiqlangan'), ('COMPLETED', 'Bajarilgan'), ('CANCELLED', 'Bekor qilingan')], default='CONFIRMED', max_length=10, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Mijoz izohi')),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='service.service', verbose_name='Xizmat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlari',
            },
        ),
    ]
