# Generated by Django 5.2.4 on 2025-07-08 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_workinghours_to_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='to_hour',
            field=models.TimeField(default=datetime.datetime(2025, 7, 8, 18, 42, 25, 120634, tzinfo=datetime.timezone.utc)),
        ),
    ]
