# Generated by Django 5.2.4 on 2025-08-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_workinghours_barber'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], default=1, unique=True),
            preserve_default=False,
        ),
    ]
