# Generated by Django 5.2.4 on 2025-07-08 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_workinghours_to_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='to_hour',
            field=models.TimeField(default=datetime.datetime(2025, 7, 8, 19, 29, 23, 209128, tzinfo=datetime.timezone.utc)),
        ),
    ]
