# Generated by Django 5.2.4 on 2025-08-12 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_workinghours_date_booking_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barber_booking', to=settings.AUTH_USER_MODEL, verbose_name='Usta'),
            preserve_default=False,
        ),
    ]
