# Generated by Django 5.2.4 on 2025-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')]),
        ),
    ]
