# Generated by Django 5.2.4 on 2025-07-12 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_workinghours_to_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='to_hour',
            field=models.TimeField(default=datetime.datetime(2025, 7, 12, 12, 42, 33, 127734, tzinfo=datetime.timezone.utc)),
        ),
    ]
