# Generated by Django 5.2.4 on 2025-07-12 06:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_workinghours_to_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time'], 'verbose_name': 'Bron', 'verbose_name_plural': 'Bronlar'},
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Mijoz izohi'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Tasdiqlangan'), ('COMPLETED', 'Bajarilgan'), ('CANCELLED', 'Bekor qilingan')], default='CONFIRMED', max_length=10, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.service', verbose_name='Xizmat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='to_hour',
            field=models.TimeField(default=datetime.datetime(2025, 7, 12, 14, 0, 38, 608165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
