# Generated by Django 5.2.4 on 2025-07-12 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_location_alter_booking_options_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='to_hour',
            field=models.TimeField(default=datetime.datetime(2025, 7, 12, 14, 9, 59, 893551, tzinfo=datetime.timezone.utc)),
        ),
    ]
