# Generated by Django 5.2.4 on 2025-07-12 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_workinghours_to_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='to_hour',
            field=models.TimeField(default=datetime.datetime(2025, 7, 12, 18, 52, 23, 225148, tzinfo=datetime.timezone.utc)),
        ),
    ]
