services:
  web:
    build: .
    entrypoint: /entrypoints.sh
    command: web
    ports: ["8000:8000"]
    volumes: [".:/app"]
    env_file: [".env"]
    extra_hosts: ["host.docker.internal:host-gateway"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "manage.py", "migrate", "--check"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    entrypoint: []
    command: ["celery","-A","src.config","worker","-l","info"]
    volumes: [".:/app"]
    env_file: [".env"]
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped
    user: "1000:1000"

  celery-beat:
    build: .
    entrypoint: []
    command: ["celery","-A","src.config","beat","-l","info",
              "--scheduler","django_celery_beat.schedulers:DatabaseScheduler"]
    volumes: [".:/app"]
    env_file: [".env"]
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped
    user: "1000:1000"
