# Generated by Django 5.2.4 on 2025-08-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='break',
            old_name='user',
            new_name='barber',
        ),
    ]
