# Generated by Django 5.2.4 on 2025-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='telegram_id',
            field=models.IntegerField(default='1001'),
            preserve_default=False,
        ),
    ]
