# Generated by Django 5.2.4 on 2025-08-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_name_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='uz', max_length=2),
        ),
    ]
