# Generated by Django 5.2.4 on 2025-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_lang',
            field=models.CharField(default='uz', max_length=10),
        ),
    ]
