# Generated by Django 5.2.4 on 2025-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_lang',
            field=models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('eng', 'Eng')], default='uz', max_length=10),
        ),
    ]
