# Generated by Django 5.2.4 on 2025-08-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_button_user_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='buttons',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
    ]
