# Generated by Django 5.2.4 on 2025-08-14 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqami / Телефонный номер'),
        ),
    ]
